### PR TITLE
Add a filter for markers, Add date and time to popup

### PR DESCRIPTION
**Pull request by bodhish**
Fix for #18

### CODE REVIEW

**Comment by aswinmohanme** [comment]
We should add filters for all the marker types and select the red and blue one by default, that would reduce the page load and the green marker issue

**Comment by bodhish** [comment]
@aswinmohanme check `6a46fb5`

**Comment by aswinmohanme** [comment]
We want both the Generic request and Rescue needed selected at the same time, at start.

If needed we can show all three filters at once, and when it's shown change the button text to hide

**Comment by aswinmohanme** [comment]
Looking good, change the color of show all request to black and rebase.

Let's push this to production :goal_net:

**Comment by bodhish** [comment]
@aswinmohanme check `92cacf4`, was a merge issue. have fixed it

**Pull request merged**
